apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartops-app
  labels:
    app: smartops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: smartops-app
  template:
    metadata:
      labels:
        app: smartops-app
    spec:
      containers:
      - name: smartops-app
        image: chiragg619/nodejs-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10